name: Deploy Server to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'landlord_online/server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        working-directory: landlord_online/server
        run: npm ci

      - name: Build
        working-directory: landlord_online/server
        run: npm run build

      - name: Zip artifact
        working-directory: landlord_online/server
        run: zip -r ../server.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: landlord_online/server


